plugins {
    id 'fabric-loom' version '0.10-SNAPSHOT'
    id 'java'
}

group = 'com.example'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    // Fabric API riippuvuus
    modImplementation "net.fabricmc:fabric-api:${project.fabricApiVersion}"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17) // Varmistetaan, että Java 17 on käytössä
    }
}

tasks {
    jar {
        archiveBaseName.set('biomemapmod')
        archiveVersion.set(version)
        from(sourceSets.main.output)
    }

    // Luo .jar tiedosto buildin aikana
    register('createJar', Jar) {
        archiveFileName.set("biomemapmod.jar")
        from(sourceSets.main.output)
    }
}

build.dependsOn(tasks.named('createJar'))
